# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:\Misc\Development\scans2reports\src\ui_scans_to_reports.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ui_addons import FileDrop

class UiScansToReports(object):
    def setupUi(self, ScansToReports):
        ScansToReports.setObjectName("ScansToReports")
        ScansToReports.resize(934, 823)
        self.main_content = QtWidgets.QWidget(ScansToReports)
        self.main_content.setStyleSheet("")
        self.main_content.setObjectName("main_content")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_content)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grp_selected_scans = QtWidgets.QGroupBox(self.main_content)
        self.grp_selected_scans.setObjectName("grp_selected_scans")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.grp_selected_scans)
        self.gridLayout_7.setContentsMargins(0, 0, 12, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.grid_selected_scans = QtWidgets.QGridLayout()
        self.grid_selected_scans.setObjectName("grid_selected_scans")
        self.tbl_selected_scans = QtWidgets.QTableWidget(self.grp_selected_scans)
        self.tbl_selected_scans.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbl_selected_scans.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tbl_selected_scans.setStyleSheet("QHeaderView::section{\n"
"            border-top:0px solid #D8D8D8;\n"
"            border-left:0px solid #D8D8D8;\n"
"            border-right:1px solid #D8D8D8;\n"
"            border-bottom: 1px solid #D8D8D8;\n"
"            background-color:white;\n"
"            padding:4px;\n"
"        }\n"
"QTableCornerButton::section{\n"
"            border-top:0px solid #D8D8D8;\n"
"            border-left:0px solid #D8D8D8;\n"
"            border-right:1px solid #D8D8D8;\n"
"            border-bottom: 1px solid #D8D8D8;\n"
"            background-color:white;\n"
"        }")
        self.tbl_selected_scans.setAlternatingRowColors(True)
        self.tbl_selected_scans.setObjectName("tbl_selected_scans")
        self.tbl_selected_scans.setColumnCount(0)
        self.tbl_selected_scans.setRowCount(0)
        self.grid_selected_scans.addWidget(self.tbl_selected_scans, 0, 0, 1, 1)
        self.btn_parse_scan_files = QtWidgets.QPushButton(self.grp_selected_scans)
        self.btn_parse_scan_files.setMinimumSize(QtCore.QSize(150, 150))
        self.btn_parse_scan_files.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.btn_parse_scan_files.setFont(font)
        self.btn_parse_scan_files.setStyleSheet("background-color: rgb(30, 126, 52);\n"
"color: #ffffff;\n"
"font-size:20pt;")
        self.btn_parse_scan_files.setObjectName("btn_parse_scan_files")
        self.grid_selected_scans.addWidget(self.btn_parse_scan_files, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.grid_selected_scans, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.grp_selected_scans, 1, 0, 1, 2)
        self.grp_scan_summary = QtWidgets.QGroupBox(self.main_content)
        self.grp_scan_summary.setObjectName("grp_scan_summary")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.grp_scan_summary)
        self.gridLayout_9.setContentsMargins(0, 0, 12, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.grid_scan_summary = QtWidgets.QGridLayout()
        self.grid_scan_summary.setObjectName("grid_scan_summary")
        self.tbl_scan_summary = QtWidgets.QTableWidget(self.grp_scan_summary)
        self.tbl_scan_summary.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tbl_scan_summary.setStyleSheet("QHeaderView::section{\n"
"            border-top:0px solid #D8D8D8;\n"
"            border-left:0px solid #D8D8D8;\n"
"            border-right:1px solid #D8D8D8;\n"
"            border-bottom: 1px solid #D8D8D8;\n"
"            background-color:white;\n"
"            padding:4px;\n"
"        }\n"
"QTableCornerButton::section{\n"
"            border-top:0px solid #D8D8D8;\n"
"            border-left:0px solid #D8D8D8;\n"
"            border-right:1px solid #D8D8D8;\n"
"            border-bottom: 1px solid #D8D8D8;\n"
"            background-color:white;\n"
"        }")
        self.tbl_scan_summary.setAlternatingRowColors(True)
        self.tbl_scan_summary.setObjectName("tbl_scan_summary")
        self.tbl_scan_summary.setColumnCount(0)
        self.tbl_scan_summary.setRowCount(0)
        self.grid_scan_summary.addWidget(self.tbl_scan_summary, 0, 0, 1, 1)
        self.btn_execute = QtWidgets.QPushButton(self.grp_scan_summary)
        self.btn_execute.setMinimumSize(QtCore.QSize(150, 150))
        self.btn_execute.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_execute.setFont(font)
        self.btn_execute.setStyleSheet("background-color: rgb(200, 35, 51);\n"
"color: #ffffff;\n"
"font-size:20pt;")
        self.btn_execute.setObjectName("btn_execute")
        self.grid_scan_summary.addWidget(self.btn_execute, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.grid_scan_summary, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.grp_scan_summary, 2, 0, 1, 2)
        self.grp_file_drop = QtWidgets.QGroupBox(self.main_content)
        self.grp_file_drop.setAcceptDrops(True)
        self.grp_file_drop.setAutoFillBackground(False)
        self.grp_file_drop.setStyleSheet("QGroupBox{\n"
"background: rgb(226, 240, 251); \n"
"border:1px solid #000000;\n"
"padding-top:10px;\n"
"}")
        self.grp_file_drop.setObjectName("grp_file_drop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.grp_file_drop)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grid_file_drop = QtWidgets.QGridLayout()
        self.grid_file_drop.setObjectName("grid_file_drop")
        self.frm_file_drop = QtWidgets.QFrame(self.grp_file_drop)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 120, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 160, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 120, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 160, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 120, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 247, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 120, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 160, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 120, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 120, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 240, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.frm_file_drop.setPalette(palette)
        self.frm_file_drop.setAcceptDrops(False)
        self.frm_file_drop.setAutoFillBackground(True)
        self.frm_file_drop.setStyleSheet("")
        self.frm_file_drop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_file_drop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_file_drop.setObjectName("frm_file_drop")
        self.gridLayout = QtWidgets.QGridLayout(self.frm_file_drop)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_file_drop = FileDrop( QtWidgets.QLabel(self.frm_file_drop), self )
        self.lbl_file_drop.setMinimumSize(QtCore.QSize(200, 150))
        self.lbl_file_drop.setAcceptDrops(True)
        self.lbl_file_drop.setStyleSheet("QLabel#lbl_file_drop{\n"
"border: 1px dashed #3490dc;\n"
"font-size:12px;\n"
"}")
        self.lbl_file_drop.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_file_drop.setWordWrap(True)
        self.lbl_file_drop.setObjectName("lbl_file_drop")
        self.gridLayout.addWidget(self.lbl_file_drop, 0, 0, 1, 1)
        self.btn_select_scan_files = QtWidgets.QPushButton(self.frm_file_drop)
        self.btn_select_scan_files.setMinimumSize(QtCore.QSize(150, 150))
        self.btn_select_scan_files.setMaximumSize(QtCore.QSize(150, 150))
        self.btn_select_scan_files.setStyleSheet("background-color: rgb(0, 98, 204);\n"
"color: #ffffff;\n"
"font-size:20pt;")
        self.btn_select_scan_files.setObjectName("btn_select_scan_files")
        self.gridLayout.addWidget(self.btn_select_scan_files, 0, 1, 1, 1)
        self.grid_file_drop.addWidget(self.frm_file_drop, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.grid_file_drop)
        self.gridLayout_2.addWidget(self.grp_file_drop, 0, 1, 1, 1)
        self.grid_data_points = QtWidgets.QGridLayout()
        self.grid_data_points.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.grid_data_points.setObjectName("grid_data_points")
        self.grp_data_points = QtWidgets.QGroupBox(self.main_content)
        self.grp_data_points.setMinimumSize(QtCore.QSize(400, 0))
        self.grp_data_points.setMaximumSize(QtCore.QSize(400, 16777215))
        self.grp_data_points.setObjectName("grp_data_points")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grp_data_points)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chk_lower_risk = QtWidgets.QCheckBox(self.grp_data_points)
        self.chk_lower_risk.setMinimumSize(QtCore.QSize(0, 25))
        self.chk_lower_risk.setMaximumSize(QtCore.QSize(16777215, 25))
        self.chk_lower_risk.setChecked(True)
        self.chk_lower_risk.setObjectName("chk_lower_risk")
        self.gridLayout_3.addWidget(self.chk_lower_risk, 5, 1, 1, 1)
        self.spnExcludeDays = QtWidgets.QSpinBox(self.grp_data_points)
        self.spnExcludeDays.setMaximum(365)
        self.spnExcludeDays.setProperty("value", 30)
        self.spnExcludeDays.setObjectName("spnExcludeDays")
        self.gridLayout_3.addWidget(self.spnExcludeDays, 8, 1, 1, 1)
        self.chk_prefill_scd = QtWidgets.QCheckBox(self.grp_data_points)
        self.chk_prefill_scd.setMinimumSize(QtCore.QSize(0, 25))
        self.chk_prefill_scd.setMaximumSize(QtCore.QSize(16777215, 25))
        self.chk_prefill_scd.setChecked(True)
        self.chk_prefill_scd.setObjectName("chk_prefill_scd")
        self.gridLayout_3.addWidget(self.chk_prefill_scd, 6, 1, 1, 1)
        self.txt_email = QtWidgets.QLineEdit(self.grp_data_points)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_email.sizePolicy().hasHeightForWidth())
        self.txt_email.setSizePolicy(sizePolicy)
        self.txt_email.setMinimumSize(QtCore.QSize(235, 25))
        self.txt_email.setMaximumSize(QtCore.QSize(235, 25))
        self.txt_email.setObjectName("txt_email")
        self.gridLayout_3.addWidget(self.txt_email, 3, 1, 1, 1)
        self.txt_command = QtWidgets.QLineEdit(self.grp_data_points)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_command.sizePolicy().hasHeightForWidth())
        self.txt_command.setSizePolicy(sizePolicy)
        self.txt_command.setMinimumSize(QtCore.QSize(235, 25))
        self.txt_command.setMaximumSize(QtCore.QSize(235, 25))
        self.txt_command.setPlaceholderText("")
        self.txt_command.setObjectName("txt_command")
        self.gridLayout_3.addWidget(self.txt_command, 0, 1, 1, 1)
        self.lbl_phone = QtWidgets.QLabel(self.grp_data_points)
        self.lbl_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_phone.setObjectName("lbl_phone")
        self.gridLayout_3.addWidget(self.lbl_phone, 2, 0, 1, 1)
        self.txt_phone = QtWidgets.QLineEdit(self.grp_data_points)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_phone.sizePolicy().hasHeightForWidth())
        self.txt_phone.setSizePolicy(sizePolicy)
        self.txt_phone.setMinimumSize(QtCore.QSize(235, 25))
        self.txt_phone.setMaximumSize(QtCore.QSize(235, 25))
        self.txt_phone.setObjectName("txt_phone")
        self.gridLayout_3.addWidget(self.txt_phone, 2, 1, 1, 1)
        self.lbl_poc = QtWidgets.QLabel(self.grp_data_points)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_poc.sizePolicy().hasHeightForWidth())
        self.lbl_poc.setSizePolicy(sizePolicy)
        self.lbl_poc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_poc.setObjectName("lbl_poc")
        self.gridLayout_3.addWidget(self.lbl_poc, 1, 0, 1, 1)
        self.lbl_command = QtWidgets.QLabel(self.grp_data_points)
        self.lbl_command.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_command.setObjectName("lbl_command")
        self.gridLayout_3.addWidget(self.lbl_command, 0, 0, 1, 1)
        self.txt_poc = QtWidgets.QLineEdit(self.grp_data_points)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_poc.sizePolicy().hasHeightForWidth())
        self.txt_poc.setSizePolicy(sizePolicy)
        self.txt_poc.setMinimumSize(QtCore.QSize(235, 25))
        self.txt_poc.setMaximumSize(QtCore.QSize(235, 25))
        self.txt_poc.setObjectName("txt_poc")
        self.gridLayout_3.addWidget(self.txt_poc, 1, 1, 1, 1)
        self.lbl_email = QtWidgets.QLabel(self.grp_data_points)
        self.lbl_email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout_3.addWidget(self.lbl_email, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.grp_data_points)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 7, 1, 1, 1)
        self.grid_data_points.addWidget(self.grp_data_points, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.grid_data_points, 0, 0, 1, 1)
        ScansToReports.setCentralWidget(self.main_content)
        self.mnu_main = QtWidgets.QMenuBar(ScansToReports)
        self.mnu_main.setGeometry(QtCore.QRect(0, 0, 934, 21))
        self.mnu_main.setObjectName("mnu_main")
        self.mnu_file = QtWidgets.QMenu(self.mnu_main)
        self.mnu_file.setObjectName("mnu_file")
        self.mnu_help = QtWidgets.QMenu(self.mnu_main)
        self.mnu_help.setObjectName("mnu_help")
        self.menuScans = QtWidgets.QMenu(self.mnu_main)
        self.menuScans.setObjectName("menuScans")
        self.menuMerge_Nessus = QtWidgets.QMenu(self.menuScans)
        self.menuMerge_Nessus.setObjectName("menuMerge_Nessus")
        ScansToReports.setMenuBar(self.mnu_main)
        self.statusbar = QtWidgets.QStatusBar(ScansToReports)
        self.statusbar.setObjectName("statusbar")
        ScansToReports.setStatusBar(self.statusbar)
        self.actionSelect = QtWidgets.QAction(ScansToReports)
        self.actionSelect.setObjectName("actionSelect")
        self.actionParse_Scans = QtWidgets.QAction(ScansToReports)
        self.actionParse_Scans.setObjectName("actionParse_Scans")
        self.actionExecute = QtWidgets.QAction(ScansToReports)
        self.actionExecute.setObjectName("actionExecute")
        self.actionExit = QtWidgets.QAction(ScansToReports)
        self.actionExit.setObjectName("actionExit")
        self.actionRefresh_Scans = QtWidgets.QAction(ScansToReports)
        self.actionRefresh_Scans.setObjectName("actionRefresh_Scans")
        self.actionClear_Scans = QtWidgets.QAction(ScansToReports)
        self.actionClear_Scans.setObjectName("actionClear_Scans")
        self.actionHelp = QtWidgets.QAction(ScansToReports)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(ScansToReports)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSplit_Nessus = QtWidgets.QAction(ScansToReports)
        self.actionSplit_Nessus.setObjectName("actionSplit_Nessus")
        self.action5_Hosts = QtWidgets.QAction(ScansToReports)
        self.action5_Hosts.setObjectName("action5_Hosts")
        self.action10_Hosts = QtWidgets.QAction(ScansToReports)
        self.action10_Hosts.setObjectName("action10_Hosts")
        self.action25_Hosts = QtWidgets.QAction(ScansToReports)
        self.action25_Hosts.setObjectName("action25_Hosts")
        self.action50_Hosts = QtWidgets.QAction(ScansToReports)
        self.action50_Hosts.setObjectName("action50_Hosts")
        self.actionAll_Hosts = QtWidgets.QAction(ScansToReports)
        self.actionAll_Hosts.setObjectName("actionAll_Hosts")
        self.action15_Hosts = QtWidgets.QAction(ScansToReports)
        self.action15_Hosts.setObjectName("action15_Hosts")
        self.mnu_file.addAction(self.actionSelect)
        self.mnu_file.addAction(self.actionParse_Scans)
        self.mnu_file.addAction(self.actionExecute)
        self.mnu_file.addSeparator()
        self.mnu_file.addAction(self.actionExit)
        self.mnu_help.addAction(self.actionHelp)
        self.mnu_help.addSeparator()
        self.mnu_help.addAction(self.actionAbout)
        self.menuMerge_Nessus.addAction(self.action5_Hosts)
        self.menuMerge_Nessus.addAction(self.action10_Hosts)
        self.menuMerge_Nessus.addAction(self.action15_Hosts)
        self.menuMerge_Nessus.addAction(self.action25_Hosts)
        self.menuMerge_Nessus.addAction(self.action50_Hosts)
        self.menuMerge_Nessus.addAction(self.actionAll_Hosts)
        self.menuScans.addAction(self.menuMerge_Nessus.menuAction())
        self.menuScans.addAction(self.actionSplit_Nessus)
        self.mnu_main.addAction(self.mnu_file.menuAction())
        self.mnu_main.addAction(self.menuScans.menuAction())
        self.mnu_main.addAction(self.mnu_help.menuAction())

        self.retranslateUi(ScansToReports)
        QtCore.QMetaObject.connectSlotsByName(ScansToReports)
        ScansToReports.setTabOrder(self.txt_command, self.txt_poc)
        ScansToReports.setTabOrder(self.txt_poc, self.txt_phone)
        ScansToReports.setTabOrder(self.txt_phone, self.txt_email)
        ScansToReports.setTabOrder(self.txt_email, self.btn_select_scan_files)
        ScansToReports.setTabOrder(self.btn_select_scan_files, self.btn_parse_scan_files)
        ScansToReports.setTabOrder(self.btn_parse_scan_files, self.btn_execute)
        ScansToReports.setTabOrder(self.btn_execute, self.tbl_selected_scans)
        ScansToReports.setTabOrder(self.tbl_selected_scans, self.tbl_scan_summary)

    def retranslateUi(self, ScansToReports):
        _translate = QtCore.QCoreApplication.translate
        ScansToReports.setWindowTitle(_translate("ScansToReports", "Scans To Reports"))
        self.grp_selected_scans.setTitle(_translate("ScansToReports", "Selected Scan Files"))
        self.btn_parse_scan_files.setText(_translate("ScansToReports", "Parse Scan \n"
"Files"))
        self.grp_scan_summary.setTitle(_translate("ScansToReports", "Scan Summary"))
        self.btn_execute.setText(_translate("ScansToReports", "Generate\n"
"Report"))
        self.grp_file_drop.setTitle(_translate("ScansToReports", "Scan Drop"))
        self.lbl_file_drop.setText(_translate("ScansToReports", " Select multiple files with the file dialog or by dragging and dropping scan files into this region "))
        self.btn_select_scan_files.setText(_translate("ScansToReports", "Select Scan\n"
"Files"))
        self.grp_data_points.setTitle(_translate("ScansToReports", "Report Data Points"))
        self.chk_lower_risk.setText(_translate("ScansToReports", "Automatically Lower Risk"))
        self.chk_prefill_scd.setText(_translate("ScansToReports", "Prefill SCD"))
        self.lbl_phone.setText(_translate("ScansToReports", "Phone"))
        self.lbl_poc.setText(_translate("ScansToReports", "Contact Name"))
        self.lbl_command.setText(_translate("ScansToReports", "Command"))
        self.lbl_email.setText(_translate("ScansToReports", "Email"))
        self.label.setText(_translate("ScansToReports", "Exclude ACAS Plugins Published Less Than X Days Ago:"))
        self.mnu_file.setTitle(_translate("ScansToReports", "&File"))
        self.mnu_help.setTitle(_translate("ScansToReports", "&Help"))
        self.menuScans.setTitle(_translate("ScansToReports", "&Scans"))
        self.menuMerge_Nessus.setTitle(_translate("ScansToReports", "Merge Nessus"))
        self.actionSelect.setText(_translate("ScansToReports", "Select Scans"))
        self.actionParse_Scans.setText(_translate("ScansToReports", "Parse Scans"))
        self.actionExecute.setText(_translate("ScansToReports", "Execute"))
        self.actionExit.setText(_translate("ScansToReports", "Exit"))
        self.actionRefresh_Scans.setText(_translate("ScansToReports", "Refresh Scans"))
        self.actionClear_Scans.setText(_translate("ScansToReports", "Clear Scans"))
        self.actionHelp.setText(_translate("ScansToReports", "Help"))
        self.actionAbout.setText(_translate("ScansToReports", "About"))
        self.actionSplit_Nessus.setText(_translate("ScansToReports", "Split Nessus"))
        self.action5_Hosts.setText(_translate("ScansToReports", "5 Hosts"))
        self.action10_Hosts.setText(_translate("ScansToReports", "10 Hosts"))
        self.action25_Hosts.setText(_translate("ScansToReports", "25 Hosts"))
        self.action50_Hosts.setText(_translate("ScansToReports", "50 Hosts"))
        self.actionAll_Hosts.setText(_translate("ScansToReports", "All Hosts"))
        self.action15_Hosts.setText(_translate("ScansToReports", "15 Hosts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScansToReports = QtWidgets.QMainWindow()
    ui = Ui_ScansToReports()
    ui.setupUi(ScansToReports)
    ScansToReports.show()
    sys.exit(app.exec_())
